fitlife/urls.py
from django.conf.urls import url

from . import views

app_name = 'fitlife'
urlpatterns = [
    url('^training/$', views.training_view, name='training'),
    url('^calculatorBMI/$', views.calculatorBMI_view, name='calculatorBMI'),
    url('^calculatorBMR/$', views.calculatorBMR_view, name='calculatorBMR'),
    url('^calculatorWeight/$', views.calculatorWeight_view, name='calculatorWeight'),
    url('^films/$', views.films_view, name='films'),
    url('^calculators/$', views.calculators_view, name='calculators'),
    url('^trainingplan/$', views.trainingplan_view, name='trainingplan'),
    url ('^products/$', views.products_view, name='products'),
    url('^dietplan/$', views.dietplan_view, name='dietplan'),
    url('^suplementation/$', views.suplementation_view, name='suplementation'),
    url('^contact/$', views.contact_view, name='contact')
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.home_view, name='home'),
    url(r'^auth/', include('loginuser.urls')),
    url(r'^fitlife/', include('fitlife.urls')),
    url(r'^admin/', admin.site.urls),
]

fitlife/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Exercise(models.Model):
    name = models.CharField(max_length=50, null=True)
    sex = models.CharField(max_length=50, null=True)
    def __str__(self):
        return self.name
    

class TrainingBreak(models.Model):
    name = models.CharField(max_length=50, null=True)
    def __str__(self):
        return self.name

class TrainingBreakExercise(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE, null=True)
    training_break = models.ForeignKey(TrainingBreak, on_delete=models.CASCADE, null=True)
    repeats = models.DecimalField(null = True, decimal_places=0, max_digits=2)
    series = models.DecimalField(null = True, decimal_places=0, max_digits=2)
    def __str__(self):
        return self.exercise.__str__ + " " + self.training_break.__str__

class Types(models.Model):
    typical = models.CharField(max_length=50, null=True)
    def __str__(self):
        return self.typical

class Products(models.Model):
    name = models.CharField(max_length=50, null=True)
    typical = models.ForeignKey(Types, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.name

fitlife/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from .models import Exercise, Products,Types


def training_view(request):
    if request.method == "POST":
        if request.POST.get("again"):
            return render(request, 'fitlife/training.html')
        else:
            is_generated = True
            sex = request.POST['sex']
            if sex == 'male':
                exercises = Exercise.objects.filter(sex="male")
            else: 
                exercises = Exercise.objects.filter(sex="female")
            context = {
                    'is_generated': is_generated,
                    'exercises': exercises,
            } 
            return render(request, 'fitlife/training.html', context)
    else:
        is_generated = False
        context = {
            'is_generated': is_generated,
        }
        return render(request, 'fitlife/training.html', context)

def calculatorBMI_view(request):
    if request.method == "POST":
        is_counted = True
        weight = float(request.POST['waga'])
        height = float(request.POST['wzrost'])
        wynik = weight/((height/100)*(height/100))
        context = {
            'is_counted': is_counted,
            'wynik': wynik,
        }
        return render(request, 'fitlife/calculatorBMI.html', context)
    else:
        is_counted = False
        context = {
            'is_counted': is_counted,
        }
        return render(request, 'fitlife/calculatorBMI.html', context)

def calculatorBMR_view(request):
    if request.method == "POST":
        if request.POST.get("count_again"):
            return render(request, 'fitlife/calculatorBMR.html')
        else:      
            is_counted = True
            sex = request.POST['sex']
            age = int(request.POST['age'])
            weight = int(request.POST['weight'])
            height = int(request.POST['height'])
            if sex == "male":
                result = (10*weight)+(6*height)-(5*age)+5
            else:
                result = (10*weight)+(6*height)-(5*age)-161
            context = {
                'is_counted': is_counted,
                'result': result,
            }
            return render(request, 'fitlife/calculatorBMR.html', context)
    else:
        is_counted = False
        context = {
            'is_counted': is_counted,
        }
    return render(request, 'fitlife/calculatorBMR.html', context)

def calculatorWeight_view(request):
    if request.method == "POST":
        if request.POST.get("count_again"):
            return render(request, 'fitlife/calculatorWeight.html')
        else:      
            is_counted = True
            sex = request.POST['sex']
            height = int(request.POST['height'])
            minimalna = float(height/100)*float(height/100)*18.5
            maksymalna = float(height/100)*float(height/100)*25
            if sex == "male":
                Broca = (height-100)*0.9
                Pottona = height-100-(height-100)/20
                Lorentza = height-100-0.25*(height-150)
            else:
                Broca = (height-100)*0.85
                Pottona = height-100-(height-100)/10
                Lorentza = height-100-0.5*(height-150)
            context = {
                'minimalna': minimalna,
                'maksymalna': maksymalna,
                'is_counted': is_counted,
                'Broca': Broca,
                'Pottona': Pottona,
                'Lorentza': Lorentza,
            }
            return render(request, 'fitlife/calculatorWeight.html', context)
    else:
        is_counted = False
        context = {
            'is_counted': is_counted,
        }
    return render(request, 'fitlife/calculatorWeight.html', context)

def films_view(request):    
    return render(request, 'fitlife/films.html')

def trainingplan_view(request):
    if request.method == "POST":
        if request.POST.get("count_again"):
            return render(request, 'fitlife/trainingplan.html')
        else:      
            is_counted = True
            trainingvalue = 0
            sex = request.POST['sex']
            if sex == "male":
                target = request.POST['target']
                if target == "strength":
                    trainingvalue = 1
                else:
                    trainingvalue = 2
            else:
                target = request.POST['target']
                if target == "strength":
                    trainingvalue = 3
                else:
                    trainingvalue = 4

            context = {
                'is_counted': is_counted,
                'trainingvalue': trainingvalue,
            }
            return render(request, 'fitlife/trainingplan.html', context)
    else:
        return render(request, 'fitlife/trainingplan.html')

def calculators_view(request):
    return render(request, 'fitlife/calculators.html')

def products_view(request):
    if request.method == "POST":
        if request.POST.get("back"):
            types=Types.objects.all()
            context = { 'types':types }
            return render(request, 'fitlife/products.html', context)
        else:
            type = request.POST['type']
            typeo = Types.objects.get(typical=type)
            products=Products.objects.filter(typical=typeo)
            context = { 'products':products,'type':type }
            return render(request, 'fitlife/products.html', context)
    
    else:
        types=Types.objects.all()
        context = { 'types':types }
        return render(request, 'fitlife/products.html', context)

def dietplan_view(request):
    if request.method == "POST":
        if request.POST.get("count_again"):
            return render(request, 'fitlife/dietplan.html')
        else:      
            is_counted = True
            dietValue = 0
            target = request.POST['target']
            activity = request.POST['activity']
            weight = int(request.POST['weight'])
            if target == "mass":
                if activity == "low":
                    kcal = weight*25*1.2+300
                    carbo = kcal/8
                    protein = kcal/16
                    fat = kcal/36
                    carbopermeal = carbo/5
                    proteinpermeal = protein/5
                    fatpermeal = fat/5

                    dietValue = 1
                elif activity == "medium":
                    kcal = weight*25*1.5+300
                    carbo = kcal/8
                    protein = kcal/16
                    fat = kcal/36
                    carbopermeal = carbo/5
                    proteinpermeal = protein/5
                    fatpermeal = fat/5

                    dietValue = 2
                else:
                    kcal = weight*25*1.7+300
                    carbo = kcal/8
                    protein = kcal/16
                    fat = kcal/36
                    carbopermeal = carbo/5
                    proteinpermeal = protein/5
                    fatpermeal = fat/5

                    dietValue = 3
            else:
                if activity == "low":
                    kcal = weight*25*1.2-300
                    carbo = kcal/8
                    protein = kcal/16
                    fat = kcal/36
                    carbopermeal = carbo/5
                    proteinpermeal = protein/5
                    fatpermeal = fat/5

                    dietValue = 4
                elif activity == "medium":
                    kcal = weight*25*1.5-300
                    carbo = kcal/8
                    protein = kcal/16
                    fat = kcal/36
                    carbopermeal = carbo/5
                    proteinpermeal = protein/5
                    fatpermeal = fat/5

                    dietValue = 5
                else:
                    kcal = weight*25*1.7-300
                    carbo = kcal/8
                    protein = kcal/16
                    fat = kcal/36
                    carbopermeal = carbo/5
                    proteinpermeal = protein/5
                    fatpermeal = fat/5

                    dietValue = 6

            context = {
                'is_counted': is_counted,
                'dietValue': dietValue,
                'kcal': kcal,
                'carbo': carbo,
                'protein': protein,
                'fat': fat,
                'carbopermeal': carbopermeal,
                'proteinpermeal': proteinpermeal,
                'fatpermeal': fatpermeal,
            }
            return render(request, 'fitlife/dietplan.html', context)
    else:
        return render(request, 'fitlife/dietplan.html')

def suplementation_view(request):
    if request.method == "POST":
        if request.POST.get("count_again"):
            return render(request, 'fitlife/suplementation.html')
        else: 
            is_counted = True
            suplementationvalue = 0
            experience = request.POST['experience']
            if experience == "Beginner":
                suplementationvalue = 2
            else:
                suplementationvalue = 1

            context = {
                'is_counted': is_counted,
                'suplementationvalue': suplementationvalue,
            }
            return render(request, 'fitlife/suplementation.html', context)
    else:
        return render(request, 'fitlife/suplementation.html')

def contact_view(request):
    return render(request, 'fitlife/contact.html')

fitlife/templates/fitlife/calculatorBMI.html
{% extends 'base.html' %}

{% block title %}CalculatorBMI{% endblock %}

{% block content %}
    {% if is_counted%}
        {% if wynik > 25 %}
            <h4>Result: {{ wynik|floatformat:2 }}<br>
            Unfortunately, you are overweight!</h4>
        {% elif wynik < 18 %}
            <h4>Result: {{ wynik|floatformat:2 }}<br>
            Unfortunately, you are underweight!</h4>
        {% else %}
            <h4>Result: {{ wynik|floatformat:2 }}<br>
            Congratulations, your weight is good for your height!</h4>
        {% endif %}
    {% else %}
        <form action="{% url 'fitlife:calculatorBMI' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <h3>Calculator BMI:</h3>
            <div class="form-group">
                <label class="col-sm-2 control-label">Weight (kg)</label>
                <div class="col-sm-10">
                    <input class="form-control" type="text" name="waga" placeholder="Weigth">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Height (cm)</label>
                <div class="col-sm-10">
                    <input class="form-control" type="text" name="wzrost"  placeholder="Height">
                </div>
            </div>
            
            <div class="text-center">
                <input type="submit" value="Count" class="btn btn-default">
            </div>
        </form>
    {% endif %}
{% endblock %}

fitlife/templates/fitlife/calculatorBMR.html
{% extends 'base.html' %}

{% block title %}CalculatorBMR{% endblock %}

{% block content %}
    {% if is_counted%}
        <h4>Your BMR is about {{ result }} calories per day.</h4>
        <form action="{% url 'fitlife:calculatorBMR' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <div class="text-center">
                <input type="submit" value="Count again" name="count_again" class="btn btn-default">
            </div>
        </form>
    {% else %}

        <form action="{% url 'fitlife:calculatorBMR' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <h3>Calculator BMR</h3>
            <div class="form-group">
                <label class="col-sm-2 control-label">Sex</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="radio" name="sex" value="male" checked="checked"> Male
                            <input type="radio" name="sex" value="female"> Female<br>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Age</label>
                <div class="col-sm-10">
                    <input class="form-control" type="text" name="age"  placeholder="Age">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Weight</label>
                <div class="col-sm-10">
                    <input class="form-control" type="text" name="weight"  placeholder="Weight">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Height</label>
                <div class="col-sm-10">
                    <input class="form-control" type="text" name="height"  placeholder="Height">
                </div>
            </div>
            <div class="text-center">
                <input type="submit" value="Count" name="count" class="btn btn-default">
            </div>
        </form>

    {% endif %}
{% endblock %}

fitlife/templates/fitlife/calculatorWeight.html
{% extends 'base.html' %}

{% block title %}Calculate your ideal weight{% endblock %}

{% block content %}
    {% if is_counted%}
        <h3>Your ideal weight</h3><br />

        <table class="table">
            <tr>
                <td>Minimum weight</td>
                <td>{{ minimalna|floatformat:2 }}</td>
            </tr>
            <tr>
                <td>by Broc</td>
                <td>{{ Broca }}</td>
            </tr>
            <tr>
                <td>by Potton</td>
                <td>{{ Pottona }}</td>
            </tr>
            <tr>
                <td>by Lorentza</td>
                <td>{{ Lorentza }}</td>
            </tr>
            <tr>
                <td>Maxiumum weight</td>
                <td>{{ maksymalna|floatformat:2 }}</td>
            </tr>
        </table>
        <form action="{% url 'fitlife:calculatorWeight' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <div class="text-center">
                <input type="submit" value="Count again" name="count_again" class="btn btn-default">
            </div>
        </form>
    {% else %}
        <form action="{% url 'fitlife:calculatorWeight' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <h3>Calculate your ideal weight</h3>
            <div class="form-group">
                <label class="col-sm-2 control-label">Sex</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="radio" name="sex" value="male" checked="checked"> Male
                            <input type="radio" name="sex" value="female"> Female<br>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Height</label>
                <div class="col-sm-10">
                    <input class="form-control" type="text" name="height"  placeholder="Height">
                </div>
            </div>
            <div class="text-center">
                <input type="submit" value="Count" name="count" class="btn btn-default">
            </div>
        </form>
    {% endif %}
{% endblock %}

fitlife/templates/fitlife/calculators.html
{% extends 'base.html' %}

{% block title %}Calculators{% endblock %}

{% block content %}
    <h3>Calculators</h3>
    <div class="calculators">
        <a href="/fitlife/calculatorBMR/" class="btn btn-primary btn-block">BMR Calculator</a><br />
        <a href="/fitlife/calculatorBMI/" class="btn btn-primary btn-block">BMI Calculator</a><br />
        <a href="/fitlife/calculatorWeight/" class="btn btn-primary btn-block">Weight Calculator</a>
    </div>
{% endblock %}

fitlife/templates/fitlife/contact.html
{% extends 'base.html' %} {% block title %}Contact{% endblock %} {% block content %}


<h3>Contact</h3>

<div>
    <address>
        <strong>The best 4 programmers ever, Inc.</strong><br />
        Wiejska 45A<br />
        15-001 Białystok<br />
        <a href="mailto:#">youcantaffordusanyway@pb.edu.pl</a>
    </address>
</div>



<div id="map"></div>

<script>
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 16,
        center: { lat: 53.118119, lng: 23.150189 }
    });
    var marker = new google.maps.Marker({
        position: { lat: 53.118119, lng: 23.150189 },
        map: map
    });
    }
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDPsvg4bdtfudOxaEuArZXNvg9E3prVb5Q&callback=initMap"></script>

{% endblock %}

fitlife/templates/fitlife/dietplan.html
{% extends 'base.html' %}

{% block title %}Diet plan generator{% endblock %}

{% block content %}

    {% if user.is_authenticated %} <!-- this page is only for registered users -->

    {% if is_counted%}
        Your daily kcal equals {{ kcal|floatformat:0 }} kcal.<br><br>
        Yours macronutrients:<br>
        protein: {{ protein|floatformat:0 }} grams<br>
        carbo: {{ carbo|floatformat:0 }} grams<br>
        fat: {{ fat|floatformat:0 }} grams<br><br>
        Yours macronutrients per meal:<br>
        protein: {{ proteinpermeal|floatformat:0 }} grams<br>
        carbo: {{ carbopermeal|floatformat:0 }} grams<br>
        fat: {{ fatpermeal|floatformat:0 }} grams<br><br>
        Products which you can use to plan your meal:<br>
        <a href="/fitlife/products/">Our products</a>
        <form action="{% url 'fitlife:trainingplan' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <div class="text-center">
                <input type="submit" name="count_again" value="Generate Again" class="btn btn-default">
            </div>
        </form>
    {% else %}
        <form action="{% url 'fitlife:dietplan' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2 control-label">Weight</label>
                <div class="col-sm-10">
                    <input class="form-control" type="text" name="weight"  placeholder="Weight">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Daily activity</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="radio" name="activity" value="low" checked="checked"> Low<br>
                            <input type="radio" name="activity" value="medium"> Medium<br>
                            <input type="radio" name="activity" value="high"> High<br>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Target</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="radio" name="target" value="mass" checked="checked"> Mass<br>
                            <input type="radio" name="target" value="reduction"> Reduction<br>
                        </label>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <input type="submit" value="Generate" class="btn btn-default">
            </div>
        </form>
    {% endif %}

    {% else %}
    <p class="bg-info larger-padding">You have to register if you want to view contents of this page.</p>
    {% endif %}
{% endblock %}

fitlife/templates/fitlife/films.html
{% extends 'base.html' %}

{% block title %}Instruction videos{% endblock %}

{% block content %}
    <h3>Chest</h3>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/lvGciMRi_zU?list=PL675498D350FA7EB5"></iframe>
    </div>
    <br />
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/FoP4sLFziF0?list=PL675498D350FA7EB5"></iframe>
    </div>
    <br />
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/aHG78PBG8d8?list=PL675498D350FA7EB5"></iframe>
    </div>
    <br><h3>Back</h3>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/O6UqLTkFJFk?list=PL675498D350FA7EB5"></iframe>
    </div>
    <br />
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/HjHIW_nTzTA?list=PL675498D350FA7EB5"></iframe>
    </div>
    <br />
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/QhzhrLWstkc?list=PL675498D350FA7EB5"></iframe>
    </div>
    <br><h3>Shoulders</h3>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/cQg2f3xfJq0?list=PL675498D350FA7EB5"></iframe>
    </div>
    <br />
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/vU50wUxydDo?list=PL675498D350FA7EB5"></iframe>
    </div>
    <br />
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/gklOqFbX-Aw?list=PL675498D350FA7EB5"></iframe>
    </div>    
{% endblock %}

fitlife/templates/fitlife/products.html
{% extends 'base.html' %} {% block title %}Products {% endblock %} {% block content %}

<form action="{% url 'fitlife:products' %}" method="post" class="form-horizontal">
    {% csrf_token %} {% if type %} {%for product in products %}

    <ul>
        <li>{{product.name}}</li>
    </ul>
{% endfor %}
        <div class="text-center">
            <input type="submit" name="back" value="back" class="btn btn-default">
        </div>
        {%else%}

        <div class="form-group">
            <label class="col-sm-2 control-label">Categories</label>
            <div class="col-sm-10">
                <div class="checkbox">
                    <label>
                            {% for type in types %}
                            <input type="radio" name="type" value="{{ type.typical }}" checked="checked"> {{ type.typical }}<br> 
                            {% endfor %}
                        </label>
                </div>
            </div>
        </div>

        <div class="text-center">
            <input type="submit" value="Generate" class="btn btn-default">
        </div>
        {% endif %} {% endblock %}

fitlife/templates/fitlife/suplementation.html
{% extends 'base.html' %}

{% block title %}Suplementation{% endblock %}

{% block content %}
    {% if suplementationvalue %}
   <h4>Daily sumplementation</h4><br /><br />
   <table class="table">
       <tbody><tr>
           <td><h4>Name</h4></td>
           <td><h4>Amount</h4></td>
        </tr></tbody>
        <tr>
           <td>Creatine (monohydrat) before/after training</td>
           <td>5g</td>
        </tr>
        {% if suplementationvalue == 1 %}        
        <tr>
           <td>BCAA before/after training</td>
           <td>5g</td>
        </tr>
        <tr>
           <td>AAKG 30 minutes before training</td>
           <td>4 caps</td>
        </tr>
        <tr>
           <td>Cytruline Before training mixed with AAKG</td>
           <td>5 caps</td>
        </tr>
        {% endif %}
        <tr>
           <td>Witamins after waking up</td>
           <td>1 cap</td>
        </tr>
        <tr>
           <td>Minerals before going to bed</td>
           <td>1 cap</td>
        </tr>
        <tr>
           <td>Protein whey after training</td>
           <td>40g</td>
        </tr>
   </table>

<br>
    <form action="{% url 'fitlife:suplementation' %}" method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="text-center">
                <input type="submit" name="count_again" value="Generate Again" class="btn btn-default">
            </div>
    </form>
    {% else %}

    <form action="{% url 'fitlife:suplementation' %}" method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label class="col-sm-2 control-label">Your experience</label>
            <div class="col-sm-10">
                <div class="checkbox">
                    <label>
                        <input type="radio" name="experience" value="Beginner" checked="checked"> Begginer<br />
                        <input type="radio" name="experience" value="Professional"> Professional
                    </label>
                </div>
            </div>
        </div>
        <div class="text-center">
            <input type="submit" value="Generate" name="again" class="btn btn-default">
        </div>
    </form>
    {% endif %}
{% endblock %}

fitlife/templates/fitlife/training.html
{% extends 'base.html' %}

{% block title %}Exercise Generator{% endblock %}

{% block content %}

    {% if user.is_authenticated %} <!-- this page is only for registered users -->

    {% if is_generated %}
        Sample exercises:<br><br>
        {% for exercise in exercises %}
            {{ exercise.name }}<br>
        {% endfor %}
        <br>
        <form action="{% url 'fitlife:training' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <div class="text-center">
                <input type="submit" value="Generate again" name="again" class="btn btn-default">
            </div>
        </form>
    {% else %}
        <form action="{% url 'fitlife:training' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2 control-label">Sex</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="radio" name="sex" value="male" checked="checked"> Male<br />
                            <input type="radio" name="sex" value="female"> Female
                        </label>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <input type="submit" value="Generate" class="btn btn-default">
            </div>
        </form>
    {% endif %}

    {% else %}
    <p class="bg-info larger-padding">You have to register if you want to view contents of this page.</p>
    {% endif %}
    
{% endblock %}